Часть 10: Аутентификация. Пользовательские сессии
carboninc/TestGuru pull request #9
Opened 2018-10-24 07:59 UTC by carboninc

2018-10-24 16:30 UTC, BubuntuClu requested changes

2018-10-24 16:30 UTC, BubuntuClu commented on app/controllers/sessions_controller.rb
> +      cookies[:root_path] = root_path
а зачем это делать? зачем перед тем как редиректить на рут, помещать это в куки?
тут смысл в том, чтоб сохранить страницу, на которую хотел зайти пользователь и после авторизации на нее редиректнуть

2018-10-24 16:30 UTC, BubuntuClu commented on app/views/shared/_nav.html.erb
> +      <li>Привет <b><%= current_user.email %></b></li>
долго искал где ты выполнил этот пункт

2018-10-24 16:42 UTC, carboninc commented on app/controllers/sessions_controller.rb
> +      cookies[:root_path] = root_path
Я не понял, что значит первоначальная страница. Она первоначальная относительно местоположения пользователя или сайта, я решил, что сайта. Твоими словами бы в задании так указать было бы гораздо яснее )

2018-10-25 12:06 UTC, psylone commented on app/controllers/sessions_controller.rb
> +      cookies[:root_path] = root_path
> Твоими словами бы в задании так указать было бы гораздо яснее )

Поправим, спасибо.

2018-10-25 12:14 UTC, psylone approved these changes

2018-10-25 12:14 UTC, psylone commented on app/controllers/sessions_controller.rb
> +      redirect_to cookies[:current_path]
В куках может оказаться `nil`.

2018-10-25 12:14 UTC, psylone commented on app/views/sessions/_form.html.erb
> +  <% if flash[:alert] %>
Делать такую проверку каждый раз неочень удобно. Будет здорово чтобы для вывода флэш сообщений было достаточно вызвать хэлпер. Кроме того, кроме `:alert` могут быть и другие типы сообщений.

2018-10-25 12:14 UTC, psylone commented on app/views/sessions/_form.html.erb
> +  <% if flash[:alert] %>
Будет удобно выводить флэш сообщения в главном шаблоне приложения.

2018-10-26 05:17 UTC, merged